"""initial schema

Revision ID: e674be9eee83
Revises: 
Create Date: 2026-09-04 14:32:13.290741
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401  (referenced by rendered JSONB columns)
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('sensitivity', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', name='sensitivity', native_enum=False, length=16), nullable=False),
    sa.Column('min_trust_score', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=96), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_sensitivity'), ['sensitivity'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_slug'), ['slug'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('max_sensitivity_ordinal', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('system_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='log_level', native_enum=False, length=16), nullable=False),
    sa.Column('logger', sa.String(length=96), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_logs'))
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_logger'), ['logger'], unique=False)

    op.create_table('policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('sensitivity', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', name='sensitivity', native_enum=False, length=16), nullable=True),
    sa.Column('min_trust_score', sa.Integer(), nullable=False),
    sa.Column('require_mfa', sa.Boolean(), nullable=False),
    sa.Column('require_known_device', sa.Boolean(), nullable=False),
    sa.Column('deny_vpn', sa.Boolean(), nullable=False),
    sa.Column('allowed_countries', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('time_window', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('effect', sa.Enum('ALLOW', 'DENY', name='policy_effect', native_enum=False, length=8), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_policies_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_policies_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies')),
    sa.UniqueConstraint('name', name=op.f('uq_policies_name'))
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_role_id'), ['role_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_strength', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'LOCKED', 'DISABLED', 'PENDING', name='account_status', native_enum=False, length=16), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('last_failed_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_city', sa.String(length=64), nullable=False),
    sa.Column('home_country', sa.String(length=2), nullable=False),
    sa.Column('home_latitude', sa.Float(), nullable=False),
    sa.Column('home_longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_account_status'), ['account_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=96), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_record_hash'), ['record_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_logs_seq'), ['seq'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('behavior_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('login_hour_sin', sa.Float(), nullable=False),
    sa.Column('login_hour_cos', sa.Float(), nullable=False),
    sa.Column('login_hour_concentration', sa.Float(), nullable=False),
    sa.Column('hour_histogram', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('weekend_login_ratio', sa.Float(), nullable=False),
    sa.Column('usual_countries', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('usual_cities', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('centroid_latitude', sa.Float(), nullable=True),
    sa.Column('centroid_longitude', sa.Float(), nullable=True),
    sa.Column('radius_km_p95', sa.Float(), nullable=False),
    sa.Column('usual_device_fingerprints', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('avg_session_minutes', sa.Float(), nullable=False),
    sa.Column('stddev_session_minutes', sa.Float(), nullable=False),
    sa.Column('avg_requests_per_minute', sa.Float(), nullable=False),
    sa.Column('stddev_requests_per_minute', sa.Float(), nullable=False),
    sa.Column('avg_distinct_resources', sa.Float(), nullable=False),
    sa.Column('typical_resources', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('model_path', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('last_trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_behavior_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_behavior_profiles'))
    )
    with op.batch_alter_table('behavior_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_behavior_profiles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavior_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=96), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REVOKED', name='device_status', native_enum=False, length=16), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('screen_resolution', sa.String(length=32), nullable=False),
    sa.Column('device_timezone', sa.String(length=48), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_devices_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('user_id', 'fingerprint', name='uq_device_user_fingerprint')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('refresh_jti', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', 'LOGGED_OUT', name='session_status', native_enum=False, length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('asn', sa.String(length=32), nullable=False),
    sa.Column('isp', sa.String(length=96), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_vpn', sa.Boolean(), nullable=False),
    sa.Column('is_datacenter', sa.Boolean(), nullable=False),
    sa.Column('ip_reputation', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_trust_score', sa.Float(), nullable=False),
    sa.Column('current_risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level', native_enum=False, length=16), nullable=False),
    sa.Column('current_action', sa.Enum('ALLOW', 'ALLOW_LIMITED', 'STEP_UP_MFA', 'BLOCK', 'REVOKE_SESSION', name='access_action', native_enum=False, length=20), nullable=False),
    sa.Column('mfa_passed', sa.Boolean(), nullable=False),
    sa.Column('mfa_failures', sa.Integer(), nullable=False),
    sa.Column('step_up_required', sa.Boolean(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('distinct_resource_count', sa.Integer(), nullable=False),
    sa.Column('denied_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_sessions_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_current_risk_level'), ['current_risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_refresh_jti'), ['refresh_jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='alert_status', native_enum=False, length=16), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], name=op.f('fk_alerts_acknowledged_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_alerts_resolved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_alerts_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('trust_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level', native_enum=False, length=16), nullable=False),
    sa.Column('action', sa.Enum('ALLOW', 'ALLOW_LIMITED', 'STEP_UP_MFA', 'BLOCK', 'REVOKE_SESSION', name='access_action', native_enum=False, length=20), nullable=False),
    sa.Column('trigger', sa.Enum('LOGIN', 'PERIODIC', 'CONTEXT_CHANGE', 'ACCESS_REQUEST', 'STEP_UP', 'ADMIN', name='score_trigger', native_enum=False, length=20), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_trust_scores_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trust_scores_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trust_scores'))
    )
    with op.batch_alter_table('trust_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_scores_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_scores_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_scores_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_scores_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_scores_trigger'), ['trigger'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_scores_user_id'), ['user_id'], unique=False)

    op.create_table('access_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('trust_score_id', sa.Uuid(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('score_at_request', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level', native_enum=False, length=16), nullable=False),
    sa.Column('decision', sa.Enum('ALLOW', 'ALLOW_LIMITED', 'STEP_UP_MFA', 'BLOCK', 'REVOKE_SESSION', name='access_action', native_enum=False, length=20), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('matched_policy', sa.String(length=128), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_anomalous', sa.Boolean(), nullable=False),
    sa.Column('scenario', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_access_requests_resource_id_resources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_access_requests_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trust_score_id'], ['trust_scores.id'], name=op.f('fk_access_requests_trust_score_id_trust_scores'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_access_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_requests'))
    )
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_granted'), ['granted'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_is_anomalous'), ['is_anomalous'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_requests_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_session_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_risk_level'))
        batch_op.drop_index(batch_op.f('ix_access_requests_resource_id'))
        batch_op.drop_index(batch_op.f('ix_access_requests_requested_at'))
        batch_op.drop_index(batch_op.f('ix_access_requests_is_anomalous'))
        batch_op.drop_index(batch_op.f('ix_access_requests_granted'))
        batch_op.drop_index(batch_op.f('ix_access_requests_decision'))
        batch_op.drop_index(batch_op.f('ix_access_requests_created_at'))

    op.drop_table('access_requests')
    with op.batch_alter_table('trust_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_trust_scores_trigger'))
        batch_op.drop_index(batch_op.f('ix_trust_scores_session_id'))
        batch_op.drop_index(batch_op.f('ix_trust_scores_score'))
        batch_op.drop_index(batch_op.f('ix_trust_scores_risk_level'))
        batch_op.drop_index(batch_op.f('ix_trust_scores_created_at'))

    op.drop_table('trust_scores')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_session_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_category'))

    op.drop_table('alerts')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_sessions_started_at'))
        batch_op.drop_index(batch_op.f('ix_sessions_refresh_jti'))
        batch_op.drop_index(batch_op.f('ix_sessions_device_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_current_risk_level'))
        batch_op.drop_index(batch_op.f('ix_sessions_created_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_devices_status'))
        batch_op.drop_index(batch_op.f('ix_devices_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_devices_created_at'))

    op.drop_table('devices')
    with op.batch_alter_table('behavior_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_behavior_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_behavior_profiles_created_at'))

    op.drop_table('behavior_profiles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_seq'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_record_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index(batch_op.f('ix_users_account_status'))

    op.drop_table('users')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_role_id'))
        batch_op.drop_index(batch_op.f('ix_policies_resource_id'))
        batch_op.drop_index(batch_op.f('ix_policies_priority'))
        batch_op.drop_index(batch_op.f('ix_policies_enabled'))
        batch_op.drop_index(batch_op.f('ix_policies_created_at'))

    op.drop_table('policies')
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_logs_logger'))
        batch_op.drop_index(batch_op.f('ix_system_logs_level'))
        batch_op.drop_index(batch_op.f('ix_system_logs_created_at'))

    op.drop_table('system_logs')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_created_at'))

    op.drop_table('roles')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_slug'))
        batch_op.drop_index(batch_op.f('ix_resources_sensitivity'))
        batch_op.drop_index(batch_op.f('ix_resources_created_at'))

    op.drop_table('resources')
    # ### end Alembic commands ###
